name: CI/CD Pipeline for AWS CS

on:
  push:
    branches:
      - main
      - test-branch

env:
  AWS_REGION: "us-east-2"
  ECR_REPO_BACKEND: "penman-backend"
  ECR_REPO_FRONTEND: "penman-frontend"
  ECS_CLUSTER: "penman-ecs"
  ECS_SERVICE: "penman-prod-service-ns2x42ro"
  ECS_TASK_DEFINITION: "penman-prod"
  CONTAINER_BACKEND_NAME: "penman-backend"
  CONTAINER_FRONTEND_NAME: "penman-frontend"

jobs:
  push-to-ecr:
    name: Build and upload to AWS ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout existing code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::307946643646:role/github-actions-deployer-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Log into AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up and push backend image to ECR
        id: build-backend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG
          echo "backend_image_uri=$ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up and push backend image to ECR
        id: build-frontend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPO_FRONTENDD:$IMAGE_TAG
          echo "backend_image_uri=$ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Render task definition with new images
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME_FRONTEND }},${{ env.CONTAINER_NAME_BACKEND }}
          image: ${{ steps.build-image-frontend.outputs.frontend_image_uri }},${{ steps.build-image-backend.outputs.backend_image_uri }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true 
